{% set name = "pybids" %}
{% set version = "0.15.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybids-{{ version }}.tar.gz
  sha256: 3a3596d3cb725431e41745f73dafb5d07603ffb1b2b29e43904b7d2da571b1d3

build:
  entry_points:
    - pybids=bids.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=30.3.0,!=61.0.0
  run:
    - bids-validator
    - click >=8.0
    - formulaic >=0.2.4,<0.4
    - nibabel >=2.1
    - num2words
    - numpy
    - pandas >=0.23
    - python >=3.7
    - scipy
    - sqlalchemy <1.4.0.dev0

test:
  imports:
    - bids
  commands:
    - pip check
    - pybids --help
  requires:
    - pip

about:
  home: http://github.com/bids-standard/pybids
  summary: 'bids: interface with datasets conforming to BIDS'
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - adelavega
    - effigies
    - sarthakpati
